In [81]:
import pandas as pd
import numpy as np

In [82]:
df=pd.read_csv('salaries_by_college_major.csv')

In [83]:
df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [84]:
df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [85]:
df.sort_index(axis=1)

,Group,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Mid-Career Median Salary,Starting Median Salary,Undergraduate Major
0,Business,42200.0,152000.0,77100.0,46000.0,Accounting
1,STEM,64300.0,161000.0,101000.0,57700.0,Aerospace Engineering
2,Business,36300.0,150000.0,71900.0,42600.0,Agriculture
3,HASS,33800.0,138000.0,61500.0,36800.0,Anthropology
4,Business,50600.0,136000.0,76800.0,41600.0,Architecture
5,HASS,28800.0,125000.0,64900.0,35800.0,Art History
6,STEM,36900.0,135000.0,64800.0,38800.0,Biology
7,Business,38800.0,147000.0,72100.0,43000.0,Business Management
8,STEM,71900.0,194000.0,107000.0,63200.0,Chemical Engineering
9,STEM,45300.0,148000.0,79900.0,42600.0,Chemistry
10,STEM,63400.0,148000.0,90500.0,53900.0,Civil Engineering
11,HASS,37500.0,143000.0,70000.0,38100.0,Communications
12,STEM,66100.0,162000.0,105000.0,61400.0,Computer Engineering
13,STEM,56000.0,154000.0,95500.0,55900.0,Computer Science
14,Business,56300.0,171000.0,88900.0,53700.0,Construction
15,HASS,32200.0,107000.0,56300.0,35000.0,Criminal Justice
16,HASS,36700.0,153000.0,56900.0,35900.0,Drama
17,Business,50600.0,210000.0,98600.0,50100.0,Economics
18,HASS,29300.0,102000.0,52000.0,34900.0,Education
19,STEM,69300.0,168000.0,103000.0,60900.0,Electrical Engineering
20,HASS,33400.0,133000.0,64700.0,38000.0,English
21,HASS,33900.0,136000.0,68500.0,37900.0,Film
22,Business,47200.0,195000.0,88300.0,47900.0,Finance
23,Business,41000.0,111000.0,62600.0,39100.0,Forestry
24,HASS,40000.0,132000.0,65500.0,41200.0,Geography
25,STEM,45000.0,156000.0,79500.0,43500.0,Geology
26,HASS,36000.0,112000.0,59800.0,35700.0,Graphic Design
27,Business,34600.0,101000.0,60600.0,38800.0,Health Care Administration
28,HASS,37000.0,149000.0,71000.0,39200.0,History
29,Business,35500.0,124000.0,57500.0,37800.0,Hospitality & Tourism
30,STEM,57100.0,173000.0,94700.0,57700.0,Industrial Engineering
31,STEM,44500.0,129000.0,74800.0,49100.0,Information Technology (IT)
32,HASS,35700.0,107000.0,53200.0,36100.0,Interior Design
33,HASS,38200.0,157000.0,80900.0,40900.0,International Relations
34,HASS,38400.0,145000.0,66700.0,35600.0,Journalism
35,STEM,45300.0,146000.0,82300.0,49200.0,Management Information Systems (MIS)
36,Business,42100.0,175000.0,79600.0,40800.0,Marketing
37,STEM,45200.0,183000.0,92400.0,45400.0,Math
38,STEM,63700.0,163000.0,93600.0,57900.0,Mechanical Engineering
39,HASS,26700.0,134000.0,55000.0,35900.0,Music
40,Business,47600.0,98300.0,67000.0,54200.0,Nursing
41,HASS,33900.0,99200.0,55300.0,39900.0,Nutrition
42,HASS,35500.0,168000.0,81200.0,39900.0,Philosophy
43,STEM,66400.0,124000.0,91700.0,74300.0,Physician Assistant
44,STEM,56000.0,178000.0,97300.0,50300.0,Physics
45,HASS,41200.0,168000.0,78200.0,40800.0,Political Science
46,HASS,31600.0,127000.0,60400.0,35900.0,Psychology
47,HASS,29700.0,96400.0,52000.0,34100.0,Religion
48,HASS,30700.0,118000.0,58200.0,36500.0,Sociology
49,HASS,31000.0,96400.0,53100.0,34000.0,Spanish
50,NaN,NaN,NaN,NaN,NaN,Source: PayScale Inc.

In [86]:
df.sort_values(by='Starting Median Salary')

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
20,English,38000.0,64700.0,33400.0,133000.0,HASS
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [87]:
df.sort_values(by='Starting Median Salary',ascending=False)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
28,History,39200.0,71000.0,37000.0,149000.0,HASS
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [88]:
df.sort_values(by='Starting Median Salary',ascending=False)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
28,History,39200.0,71000.0,37000.0,149000.0,HASS
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [89]:
df.count(axis=0)

Undergraduate Major                  51
Starting Median Salary               50
Mid-Career Median Salary             50
Mid-Career 10th Percentile Salary    50
Mid-Career 90th Percentile Salary    50
Group                                50
dtype: int64

In [90]:
df.count(axis=0).median

<bound method Series.median of Undergraduate Major                  51
Starting Median Salary               50
Mid-Career Median Salary             50
Mid-Career 10th Percentile Salary    50
Mid-Career 90th Percentile Salary    50
Group                                50
dtype: int64>

In [91]:
df.sort_values(by='Starting Median Salary',ascending=False)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
28,History,39200.0,71000.0,37000.0,149000.0,HASS
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [92]:
df.iterrows()

In [93]:
len(df.iterrows())

TypeError: object of type 'generator' has no len()

In [94]:
df.shape

(51, 6)

In [95]:
df.isna

<bound method DataFrame.isna of                      Undergraduate Major  Starting Median Salary  \
0                             Accounting                 46000.0
1                  Aerospace Engineering                 57700.0
2                            Agriculture                 42600.0
3                           Anthropology                 36800.0
4                           Architecture                 41600.0
5                            Art History                 35800.0
6                                Biology                 38800.0
7                    Business Management                 43000.0
8                   Chemical Engineering                 63200.0
9                              Chemistry                 42600.0
10                     Civil Engineering                 53900.0
11                        Communications                 38100.0
12                  Computer Engineering                 61400.0
13                      Computer Science                 55900.0
14                          Construction                 53700.0
15                      Criminal Justice                 35000.0
16                                 Drama                 35900.0
17                             Economics                 50100.0
18                             Education                 34900.0
19                Electrical Engineering                 60900.0
20                               English                 38000.0
21                                  Film                 37900.0
22                               Finance                 47900.0
23                              Forestry                 39100.0
24                             Geography                 41200.0
25                               Geology                 43500.0
26                        Graphic Design                 35700.0
27            Health Care Administration                 38800.0
28                               History                 39200.0
29                 Hospitality & Tourism                 37800.0
30                Industrial Engineering                 57700.0
31           Information Technology (IT)                 49100.0
32                       Interior Design                 36100.0
33               International Relations                 40900.0
34                            Journalism                 35600.0
35  Management Information Systems (MIS)                 49200.0
36                             Marketing                 40800.0
37                                  Math                 45400.0
38                Mechanical Engineering                 57900.0
39                                 Music                 35900.0
40                               Nursing                 54200.0
41                             Nutrition                 39900.0
42                            Philosophy                 39900.0
43                   Physician Assistant                 74300.0
44                               Physics                 50300.0
45                     Political Science                 40800.0
46                            Psychology                 35900.0
47                              Religion                 34100.0
48                             Sociology                 36500.0
49                               Spanish                 34000.0
50                 Source: PayScale Inc.                     NaN

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                    77100.0                            42200.0
1                   101000.0                            64300.0
2                    71900.0                            36300.0
3                    61500.0                            33800.0
4                    76800.0                            50600.0
5                    64900.0                            28800.0
6                    64800.0                            36900.0
7                    72100.0                            38800.0
8                   107000.0                            71900.0
9                    79900.0                            45300.0
10                   90500.0                            63400.0
11                   70000.0                            37500.0
12                  105000.0                            66100.0
13                   95500.0                            56000.0
14                   88900.0                            56300.0
15                   56300.0                            32200.0
16                   56900.0                            36700.0
17                   98600.0                            50600.0
18                   52000.0                            29300.0
19                  103000.0                            69300.0
20                   64700.0                            33400.0
21                   68500.0                            33900.0
22                   88300.0                            47200.0
23                   62600.0                            41000.0
24                   65500.0                            40000.0
25                   79500.0                            45000.0
26                   59800.0                            36000.0
27                   60600.0                            34600.0
28                   71000.0                            37000.0
29                   57500.0                            35500.0
30                   94700.0                            57100.0
31                   74800.0                            44500.0
32                   53200.0                            35700.0
33                   80900.0                            38200.0
34                   66700.0                            38400.0
35                   82300.0                            45300.0
36                   79600.0                            42100.0
37                   92400.0                            45200.0
38                   93600.0                            63700.0
39                   55000.0                            26700.0
40                   67000.0                            47600.0
41                   55300.0                            33900.0
42                   81200.0                            35500.0
43                   91700.0                            66400.0
44                   97300.0                            56000.0
45                   78200.0                            41200.0
46                   60400.0                            31600.0
47                   52000.0                            29700.0
48                   58200.0                            30700.0
49                   53100.0                            31000.0
50                       NaN                                NaN

    Mid-Career 90th Percentile Salary     Group
0                            152000.0  Business
1                            161000.0      STEM
2                            150000.0  Business
3                            138000.0      HASS
4                            136000.0  Business
5                            125000.0      HASS
6                            135000.0      STEM
7                            147000.0  Business
8                            194000.0      STEM
9                            148000.0      STEM
10                           148000.0      STEM
11                           143000.0      HASS
12                           162000.0      STEM
13                           154000.0      STEM
14                           171000.0  Business
15                           107000.0      HASS
16                           153000.0      HASS
17                           210000.0  Business
18                           102000.0      HASS
19                           168000.0      STEM
20                           133000.0      HASS
21                           136000.0      HASS
22                           195000.0  Business
23                           111000.0  Business
24                           132000.0      HASS
25                           156000.0      STEM
26                           112000.0      HASS
27                           101000.0  Business
28                           149000.0      HASS
29                           124000.0  Business
30                           173000.0      STEM
31                           129000.0      STEM
32                           107000.0      HASS
33                           157000.0      HASS
34                           145000.0      HASS
35                           146000.0      STEM
36                           175000.0  Business
37                           183000.0      STEM
38                           163000.0      STEM
39                           134000.0      HASS
40                            98300.0  Business
41                            99200.0      HASS
42                           168000.0      HASS
43                           124000.0      STEM
44                           178000.0      STEM
45                           168000.0      HASS
46                           127000.0      HASS
47                            96400.0      HASS
48                           118000.0      HASS
49                            96400.0      HASS
50                                NaN       NaN  >

In [96]:
df=df.dropna(axis=0,how='any')

In [97]:
df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [98]:
df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [99]:
m=df['Mid-Career Median Salary'].min()
m=int(m)
m

52000

In [100]:
df[df['Mid-Career Median Salary']==m]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS

In [101]:
newdf=df.copy()

In [102]:
diff_col=df['Mid-Career 90th Percentile Salary']-df['Mid-Career 10th Percentile Salary']
diff_col

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [103]:
newdf.insert(1,'Difference',diff_col)

In [104]:
newdf.sort_values(by='Difference')

,Undergraduate Major,Difference,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
23,Forestry,70000.0,39100.0,62600.0,41000.0,111000.0,Business
32,Interior Design,71300.0,36100.0,53200.0,35700.0,107000.0,HASS
18,Education,72700.0,34900.0,52000.0,29300.0,102000.0,HASS
15,Criminal Justice,74800.0,35000.0,56300.0,32200.0,107000.0,HASS
26,Graphic Design,76000.0,35700.0,59800.0,36000.0,112000.0,HASS
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
29,Hospitality & Tourism,88500.0,37800.0,57500.0,35500.0,124000.0,Business
24,Geography,92000.0,41200.0,65500.0,40000.0,132000.0,HASS
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
5,Art History,96200.0,35800.0,64900.0,28800.0,125000.0,HASS
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
6,Biology,98100.0,38800.0,64800.0,36900.0,135000.0,STEM
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
20,English,99600.0,38000.0,64700.0,33400.0,133000.0,HASS
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
21,Film,102100.0,37900.0,68500.0,33900.0,136000.0,HASS
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
11,Communications,105500.0,38100.0,70000.0,37500.0,143000.0,HASS
34,Journalism,106600.0,35600.0,66700.0,38400.0,145000.0,HASS
39,Music,107300.0,35900.0,55000.0,26700.0,134000.0,HASS
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
28,History,112000.0,39200.0,71000.0,37000.0,149000.0,HASS
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
16,Drama,116300.0,35900.0,56900.0,36700.0,153000.0,HASS
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business

In [105]:
overall_median_salary=df['Mid-Career Median Salary'].median()
overall_median_salary=int(overall_median_salary)
overall_median_salary

72000

In [106]:
newdf[newdf['Mid-Career Median Salary']>overall_median_salary].sort_values(by='Difference',ascending=False)

,Undergraduate Major,Difference,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM

In [108]:
newdf.groupby('Group').mean()

TypeError: agg function failed [how->mean,dtype->object]